gps:
  ip: localhost
  port: 9090
rovers: 
  - name: Elcaduck
    ip: '192.168.1.30'
    port: 9001
    tag: 50
  - name: Rover01
    ip: '192.168.1.31'
    port: 9001
    tag: 51
  - name: Rover02
    ip: '192.168.1.32'
    port: 9001
    tag: 52
  - name: Rover03
    ip: '192.168.1.33'
    port: 9001
    tag: 53
  - name: Rover04
    ip: '192.168.1.34'
    port: 9001
    tag: 54
  - name: Rover05
    ip: '192.168.1.35'
    port: 9001
    tag: 55